// <auto-generated />
using System;
using LearningP;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearningP.Migrations
{
    [DbContext(typeof(StampInfoContext))]
    [Migration("20220716085554_test1")]
    partial class test1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LearningP.StampInfo", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StampGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Key");

                    b.ToTable("Stamps");

                    b.HasData(
                        new
                        {
                            Key = new Guid("72a0bad6-e871-4687-b62c-955a9f2bac7c"),
                            Reason = "Testing",
                            StampGuid = new Guid("b375d261-a40f-4277-9e95-abd305f5ebfd"),
                            Time = new DateTime(2022, 7, 16, 11, 55, 54, 50, DateTimeKind.Local).AddTicks(4992)
                        },
                        new
                        {
                            Key = new Guid("8caa015a-140b-47f6-84cc-029f6b204922"),
                            Reason = "Reason",
                            StampGuid = new Guid("f02975d1-51e8-4a21-902b-55b819497321"),
                            Time = new DateTime(2022, 7, 16, 11, 55, 54, 50, DateTimeKind.Local).AddTicks(5010)
                        });
                });

            modelBuilder.Entity("LearningP.TestClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StampGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Tests");
                });
#pragma warning restore 612, 618
        }
    }
}
